services:
  couchbase:
    image: couchbase:community-7.6.2
    container_name: couchbase
    ports:
      - "8091-8097:8091-8097"
      - "9123:9123"
      - "11210:11210"
    networks:
      - localnet

  couchbase-node1:
    image: couchbase:community-7.6.2
    container_name: couchbase-node1
    ports:
      - "18091:8091"
    depends_on:
      - couchbase
    networks:
      - localnet

  couchbase-node2:
    image: couchbase:community-7.6.2
    container_name: couchbase-node2
    ports:
      - "28091:8091"
    depends_on:
      - couchbase
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
